name: {{service_name}}
default_language: uz
operator_number_regex: /^998((97|88)\d{7})$/
otp_pin_regex: /^\d{4}$/
otp_rid_regex: /^\d+:\d+$/

otp:
  url: "{{otp_url}}"
  timeout: 10
  pause: 1
  send: 'format=json&msisdn={{msisdn}}&language={{language}}&mod={{mod}}'
  validate: 'format=json&msisdn={{msisdn}}&language={{language}}&mod={{mod}}&rid={{rid}}&pin={{pin}}'

header_enrichment_key: msisdn

campaign:
  camp:
    banana: groupA